# Generated by Django 2.1.2 on 2018-11-25 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Raw', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Icon', models.CharField(max_length=10)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=1000)),
                ('Order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmojiKeyword',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Emoji', models.CharField(max_length=250)),
                ('Keyword', models.CharField(max_length=250)),
                ('SuggestedByUser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IgnoredPhrases',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Phrase', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Value', models.BooleanField(default=True)),
                ('Conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Conversion', verbose_name='Processed Tweet')),
            ],
        ),
    ]
