# Generated by Django 2.1.2 on 2018-10-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emoji',
            name='Text',
        ),
        migrations.AddField(
            model_name='emoji',
            name='Description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emoji',
            name='Icon',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emoji',
            name='Name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
