# Generated by Django 2.1.2 on 2018-11-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181021_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredPhrases',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Phrase', models.CharField(max_length=250)),
            ],
        ),
    ]
